#!/bin/bash

WORKINGDRAFT="./workingdraft.md"

echo $WORKINGDRAFT

COUNTMESSAGE=`wc -w $WORKINGDRAFT`" "`date`
echo $COUNTMESSAGE >> wordcount.txt

echo "----------------------------------------"
echo 
echo $* "    " `wc -w $WORKINGDRAFT`
echo
echo "----------------------------------------"

git add . -A 
git commit -m "$* `wc -w $WORKINGDRAFT`"
git push 


COUNTMESSAGE=`wc -w $WORKINGDRAFT`" "`date`